### ISSUE TITLE
NSFW Project

### ISSUE THREAD

**Issue by dreamsoftech** [MichaelGrigoryan25/py-nudec#1]
Hi @michaelgrigoryan25 
I am a CTO at WALTB and we are building video chatting application.
In our application, we need to implement NSFW processing and I need your help.
I tried yahoo NSFW engine and it's a little slow than we need.
We need to process image within 30 ~ 50 ms but yahoo engine takes 70 ~ 80ms.
So I tried to find alternative solution and I am reaching out to you.
Can we schedule a call and discuss the project?
My email is andrew@waltb.co.
My github handle is dreamsoftech

Thanks,
Andrew

**Comment by mikayelgr** [comment]
Hi @dreamsoftech, hope you're doing well.
Thanks for taking the time and reaching out to me.

> We need to process image within 30 ~ 50 ms but yahoo engine takes 70 ~ 80ms.

For `py-nudec` it takes approximately **900ms** to analyze an image and send back the boolean response. The amount of time needed will rise by `900n`ms depending on the number of images you upload. Keep in mind that HTTP contributes to the amount of time needed to process every single image, that you sent in the `form-data` payload. Doing it with a compiled language such as Go, also may help you heavily reduce the processing time.

> So I tried to find alternative solution and I am reaching out to you. Can we schedule a call and discuss the project?

Sure, could you please specify what do you need to know about the project? If, you cannot ask your question here, then sure, we can schedule a call.

**Comment by dreamsoftech** [comment]
Hi @michaelgrigoryan25 
Thanks for your reply.
We are not using HTTP API.
We want to build own package by using c++ because we build the client app by using c++.
There are bunch of NSFW engines such as yahoo NSFW engine and NudeNet.
But the problem is it is slower than we need.

So the task is
1. Optimize the datasets and increase the speed.
    Since it is video chatting application, it must be less than 30 ~ 50 ms per image. And we can ignore FEMALE_BELLY, MALE_BELLY or BUTTOCKS. We can just filter out sensitive parts.
2.Build the NSFW library or package by using C++ after optimizing NSFW engine.

Looking forward to your reply.
Thanks,

**Comment by dreamsoftech** [comment]
And please let me know your contact so we can schedule a call.

**Comment by mikayelgr** [comment]
Sorry but I have very basic experience in working with C++. You mentioned your requirements without telling how `py-nudec` relates to them. Could you please elaborate a bit?

**Comment by dreamsoftech** [comment]
If you can make the NSFW engine faster, it's enough. We have C++ engineers in our team so it's not a big deal.

**Comment by mikayelgr** [comment]
I didn't understand. Is this some sort of a job offer?

**Comment by dreamsoftech** [comment]
Yes.

**Comment by mikayelgr** [comment]
You can connect with me either via my Discord at `michaelgrigoryan25#0410` or with my email address **_michael.grigoryan25[at]gmail.com_**

**Comment by mikayelgr** [comment]
I haven't received any emails from you @dreamsoftech
